import streamlit as st
import geopandas as gpd
import pandas as pd
import pygris


@st.cache_data
def fix_park_types():
    parks = load_parks()
    housing = load_housing()

    """parks_types.ipynb

    Automatically generated by Colab.

    Original file is located at
        https://colab.research.google.com/drive/1irI8pQ7hlxp5vF4s6qaSbixfhJcwx4KV

    #TYPES OF PARKS
    """

    ## CLEANING PARKS DATA

    # filtered for typical "park" parks
    parks = parks[parks['typecategory'].isin(['Community Park', 'Flagship Park', 'Neighborhood Park'])]
    parks_geo = parks.loc[:,'geometry'] # select geometry column for plotting

    ## CLEANING HOUSING DATA ##

    # renaming columns to snake case
    housing = housing.rename(columns = {'Low Income Units': 'low_income_units', 'Very Low Income Units':'v_low_income_units', 'Extremely Low Income Units':'e_low_income_units'})

    # dropping any NAs in lat/lon (can't have NAs for plots)
    housing = housing.dropna(subset = ['Latitude', 'Longitude'])

    # creating total "low income units" variables (= low income + very low + extremely low)
    housing['low_income_units_sum'] = housing['low_income_units'] + housing['v_low_income_units'] + housing['e_low_income_units']

    ## CLEANING HOUSING DATA CONT'D ##

    # rename project start and completion dates to snake case
    housing = housing.rename(columns = {'Project Start Date': 'proj_start', 'Project Completion Date':'proj_complete'})

    # split date column into year/month/day for filtering
    housing[['month_complete', 'day_complete', 'year_complete']] = housing.proj_complete.str.split("/", expand = True)

    # drop any NAs
    housing = housing.dropna(subset = ['year_complete'])
    housing = housing.dropna(subset = ['month_complete'])
    housing = housing.dropna(subset = ['day_complete'])


    # making date data into integer
    housing['year_complete'] = housing['year_complete'].astype(int)
    housing['month_complete'] = housing['month_complete'].astype(int)
    housing['day_complete'] = housing['day_complete'].astype(int)


    # filtering for projects completed in SECOND HALF OF 2025
    housing_filter = housing[housing['year_complete'] == 2025]
    housing_filter = housing_filter[housing_filter['month_complete'] >= 7]

    ## AFFORDABILITY RATES ##

    housing_filter['Total Units'] = [row.replace(',', '') for row in housing_filter['Total Units']] # replace commas in numbers w/ nothing

    # make total units an integer
    housing_filter['Total Units'] = housing_filter['Total Units'].astype(int)

    # calculate %age of building that is low-income
    housing_filter['affordability'] = housing_filter['low_income_units_sum'] / housing_filter['Total Units']

    # keep units with at least 20% low-income units
    housing_filter = housing_filter[housing_filter['affordability'] >= 0.2]

    parks['geometry_2'] = parks['geometry'] # copy geometry
    parks_geo = parks.copy() # copy df
    parks_geo['geometry_2'] = parks_geo['geometry_2'].to_crs(2263)

    housing_filter = gpd.GeoDataFrame(housing_filter,
                                    geometry=gpd.points_from_xy(housing_filter.Longitude, housing_filter.Latitude), crs='4326')

    housing_filter['geometry_2'] = housing_filter['geometry'].to_crs(2263)

    housing_geo = gpd.GeoDataFrame(geometry=gpd.GeoSeries(housing_filter['geometry_2']))

    housing_filter = housing_filter.reset_index()

    housing_geo = housing_geo.reset_index()

    housing2 = housing_geo.merge(housing_filter, on = 'index', how = 'inner')

    parks_geo = parks_geo.set_geometry('geometry_2')

    housing2 = housing2.set_geometry('geometry_2')

    return [housing_filter, gpd.sjoin_nearest(housing2, parks_geo, how = 'inner', distance_col='distance')]

@st.cache_data
def fix_park_accessibility():
    boroughs = load_boroughs()
    boroughs_viz = boroughs.to_crs(epsg=4326)

    parks_clean = load_parks()
    parks_clean = parks_clean.to_crs(epsg=4326)

    nyc_final_gdf = load_popraw()
    tracts_2263 = nyc_final_gdf.to_crs(epsg=2263)
    boroughs_2263 = boroughs.to_crs(epsg=2263)

    # Note: Clipping to fix the "Sea Fill" issue
    tracts_land_only = gpd.clip(tracts_2263, boroughs_2263)

    # Step B: Recalculate Metrics
    parks_2263 = parks_clean.to_crs(epsg=2263)
    parks_int = gpd.overlay(parks_2263, tracts_land_only, how='intersection')

    # Note: Summing area and renaming to avoid 'geometry' collision
    park_area_val = parks_int.groupby('GEOID')['geometry'].apply(lambda x: x.area.sum() / 27878400).reset_index()
    park_area_val = park_area_val.rename(columns={'geometry': 'park_area_sqmi'})

    # Step C: Merge & Fix Active Geometry
    final_gdf = tracts_land_only.merge(park_area_val, on='GEOID', how='left').fillna(0)

    # Note: Explicitly setting the geometry column after merge
    # This ensures GeoPandas knows which column to use for to_crs()
    final_gdf = final_gdf.set_geometry('geometry')

    # Step D: Recalculate Metrics on Land-Only Geometry
    final_gdf['tract_area_sqmi'] = final_gdf.geometry.area / 27878400
    final_gdf['green_coverage_pct'] = (final_gdf['park_area_sqmi'] / final_gdf['tract_area_sqmi']) * 100

    # Step E: 2x2 Binning (Median Split)
    final_gdf['pop_density'] = final_gdf['total_pop'] / final_gdf['tract_area_sqmi']
    for col in ['x_label', 'y_label', 'bi_class']:
        if col in final_gdf.columns:
            final_gdf.drop(columns=[col], inplace=True)
    final_gdf['x_label'] = pd.qcut(final_gdf['pop_density'].rank(method='first'), 2, labels=['1', '2'])
    final_gdf['y_label'] = pd.qcut(final_gdf['green_coverage_pct'].rank(method='first'), 2, labels=['1', '2'])
    final_gdf['bi_class'] = final_gdf['x_label'].astype(str) + final_gdf['y_label'].astype(str)

    # Now to_crs() will work perfectly
    return final_gdf.to_crs(epsg=4326)


@st.cache_data
def load_parks():
    return gpd.read_file("csv_data/Parks_Properties_20260414.geojson")

@st.cache_data
def load_housing():
    return pd.read_csv("csv_data/Affordable_Housing_Production_by_Building_20260415.csv")

@st.cache_data
def load_boroughs():
    return gpd.read_file("csv_data/Borough_Boundaries_20260416.geojson")

@st.cache_data
def load_monuments():
    return pd.read_csv("csv_data/NYC_Parks_Monuments_20260416.csv")

@st.cache_data
def load_trees():
    return pd.read_csv("csv_data/trees_sample.csv")

@st.cache_data
def load_popraw():
    # ==========================================
    # 1. Data Retrieval
    # ==========================================
    from pygris.data import get_census

    # Target County FIPS for the 5 boroughs of NYC
    nyc_fips = ["005", "047", "061", "081", "085"]

    # Fetching Total Population data
    nyc_pop_raw = get_census(
        dataset = "acs/acs5",
        variables = "B01003_001E",
        year = 2022,
        params = {
            "for": "tract:*",
            "in": "state:36"
        },
        return_geoid = True
    )

    # ==========================================
    # 2. String Slicing Filter
    # ==========================================
    # Note: GEOID is structured as SSCCCTTTTTT (S=State, C=County, T=Tract)
    # We slice characters from index 2 to 5 to extract the County FIPS code.
    nyc_pop_data = nyc_pop_raw[nyc_pop_raw['GEOID'].str[2:5].isin(nyc_fips)].copy()

    # Note: Renaming for clarity and ensuring the population is numeric
    nyc_pop_data = nyc_pop_data.rename(columns={"B01003_001E": "total_pop"})
    nyc_pop_data['total_pop'] = pd.to_numeric(nyc_pop_data['total_pop'], errors='coerce').fillna(0)

    # ==========================================
    # 3. Geography Retrieval & Merging
    # ==========================================
    # Note: Fetching NYC Tract boundaries specifically for the 5 boroughs
    # This provides the 'geometry' column needed for mapping.
    nyc_geometry = pygris.tracts(state = "NY", county = ["Bronx", "Kings", "New York", "Queens", "Richmond"], year = 2022)

    # Note: Merging the population data with the geometry based on the common GEOID
    # This combined GeoDataFrame is the foundation for your Bivariate Map.
    nyc_final_gdf = nyc_geometry.merge(nyc_pop_data[['GEOID', 'total_pop']], on = "GEOID")

    # Note: Projecting to EPSG:2263 (NY Long Island) for accurate density calculations
    # This is mandatory for QMSS-level spatial analysis.
    nyc_final_gdf = nyc_final_gdf.to_crs(2263)

    # Calculate Population Density (People per Square Mile)
    # Note: 1 sq mile = 27,878,400 sq feet
    nyc_final_gdf['pop_density'] = (nyc_final_gdf['total_pop'] / (nyc_final_gdf.geometry.area / 27878400))

    return nyc_final_gdf