# -*- coding: utf-8 -*-
import geopandas as gpd
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
import mapclassify as mc
import folium as fol
import folium.plugins
import branca as br
import os
import altair as alt
from vega_datasets import data
from folium.plugins import MarkerCluster
from shapely.geometry import Point
from prettytable import PrettyTable
import shapely
from shapely import LineString, Point, Polygon
import numpy as np
from charts.data_loader import load_parks, load_housing

def park_types_chart():
    parks = load_parks()
    housing = load_housing()





    """parks_types.ipynb

    Automatically generated by Colab.

    Original file is located at
        https://colab.research.google.com/drive/1irI8pQ7hlxp5vF4s6qaSbixfhJcwx4KV

    #TYPES OF PARKS
    """

    ## CLEANING PARKS DATA

    # filtered for typical "park" parks
    parks = parks[parks['typecategory'].isin(['Community Park', 'Flagship Park', 'Neighborhood Park'])]
    parks_geo = parks.loc[:,'geometry'] # select geometry column for plotting

    ## CLEANING HOUSING DATA ##

    # renaming columns to snake case
    housing = housing.rename(columns = {'Low Income Units': 'low_income_units', 'Very Low Income Units':'v_low_income_units', 'Extremely Low Income Units':'e_low_income_units'})

    # dropping any NAs in lat/lon (can't have NAs for plots)
    housing = housing.dropna(subset = ['Latitude', 'Longitude'])

    # creating total "low income units" variables (= low income + very low + extremely low)
    housing['low_income_units_sum'] = housing['low_income_units'] + housing['v_low_income_units'] + housing['e_low_income_units']

    ## CLEANING HOUSING DATA CONT'D ##

    # rename project start and completion dates to snake case
    housing = housing.rename(columns = {'Project Start Date': 'proj_start', 'Project Completion Date':'proj_complete'})

    # split date column into year/month/day for filtering
    housing[['month_complete', 'day_complete', 'year_complete']] = housing.proj_complete.str.split("/", expand = True)

    # drop any NAs
    housing = housing.dropna(subset = ['year_complete'])
    housing = housing.dropna(subset = ['month_complete'])
    housing = housing.dropna(subset = ['day_complete'])


    # making date data into integer
    housing['year_complete'] = housing['year_complete'].astype(int)
    housing['month_complete'] = housing['month_complete'].astype(int)
    housing['day_complete'] = housing['day_complete'].astype(int)


    # filtering for projects completed in SECOND HALF OF 2025
    housing_filter = housing[housing['year_complete'] == 2025]
    housing_filter = housing_filter[housing_filter['month_complete'] >= 7]

    ## AFFORDABILITY RATES ##

    housing_filter['Total Units'] = [row.replace(',', '') for row in housing_filter['Total Units']] # replace commas in numbers w/ nothing

    # make total units an integer
    housing_filter['Total Units'] = housing_filter['Total Units'].astype(int)

    # calculate %age of building that is low-income
    housing_filter['affordability'] = housing_filter['low_income_units_sum'] / housing_filter['Total Units']

    # keep units with at least 20% low-income units
    housing_filter = housing_filter[housing_filter['affordability'] >= 0.2]

    parks['geometry_2'] = parks['geometry'] # copy geometry
    parks_geo = parks.copy() # copy df
    parks_geo['geometry_2'] = parks_geo['geometry_2'].to_crs(2263)

    housing_filter = gpd.GeoDataFrame(housing_filter,
                                    geometry=gpd.points_from_xy(housing_filter.Longitude, housing_filter.Latitude), crs='4326')

    housing_filter['geometry_2'] = housing_filter['geometry'].to_crs(2263)

    housing_geo = gpd.GeoDataFrame(geometry=gpd.GeoSeries(housing_filter['geometry_2']))

    housing_filter = housing_filter.reset_index()

    housing_geo = housing_geo.reset_index()

    housing2 = housing_geo.merge(housing_filter, on = 'index', how = 'inner')

    parks_geo = parks_geo.set_geometry('geometry_2')

    housing2 = housing2.set_geometry('geometry_2')

    closest = gpd.sjoin_nearest(housing2, parks_geo, how = 'inner', distance_col='distance')

    closest['park_centroids'] = [row.centroid for row in closest['geometry']]
    closest['park_lat'] = [row.y for row in closest['park_centroids']]
    closest['park_long'] = [row.x for row in closest['park_centroids']]

    parks = parks.set_geometry('geometry')

    parks = gpd.GeoDataFrame(geometry=gpd.GeoSeries(parks['geometry']))

    closest['distance'] = [round(row, 1) for row in closest['distance']]

    closest['distance_ft'] = closest['distance'] / 5280

    closest['distance_ft'] = [round(row, 1) for row in closest['distance_ft']]

    ## HOUSING + PARKS DATA

    # Create sample data for NYC landmarks
    housing_landmarks = pd.DataFrame({
        'street': housing_filter['Street'], # name = CZ_NAME = county name
        'lat': housing_filter['Latitude'], # latitude = BEGIN_LAT
        'lon': housing_filter['Longitude'], # longitude = BEGIN_LON
        'liu': housing_filter['low_income_units_sum'], # type = EVENT_TYPE = heat, flood, etc.
    })

    m = folium.Map(
        location=[40.78, -73.94],
        zoom_start=13,
        tiles='CartoDB positron' # I like positron for these maps
    )

    fg1 = folium.FeatureGroup(name="Housing Projects", show=True).add_to(m)
    for idx, row in housing_landmarks.iterrows():
        popup_content = f"""
        <h4>{row['street']}</h4>
        <b>Low Income Housing:</b> {row['liu']}<br>
        """

        folium.CircleMarker(
            location=[row['lat'], row['lon']],
            radius = 4.2,
            color="#527588",
            stroke=False,
            fill=True,
            fill_opacity=1,
            opacity=.5,
            popup=folium.Popup(popup_content, max_width=300),
            tooltip= f"{row['street']} | {row['liu']} low-income units",
            ).add_to(fg1)


    distance_landmarks = pd.DataFrame({
        'park_lat': closest['park_lat'], # latitude = BEGIN_LAT
        'park_long': closest['park_long'], # longitude = BEGIN_LON
        'house_lat': closest['Latitude'],
        'house_long' : closest['Longitude'],
        'park_name' : closest['name311'],
        'distance' : closest['distance_ft']
    })

    fg = folium.FeatureGroup(name="Distances", show=True).add_to(m)
    for idx, row in distance_landmarks.iterrows():
        popup_content = f"""
        <h4>{row['park_name']}</h4>
        <b>Closest Park:</b> {row['park_name']}<br>
        """

        folium.PolyLine(
            locations=[[row['park_lat'], row['park_long']], [row['house_lat'], row['house_long']]],
            color="#527588",
            weight=2,
            popup=folium.Popup(popup_content, max_width=300),
            tooltip= f"{row['park_name']} is the closest park | {row['distance']} miles",
            ).add_to(fg)

    fg2 = folium.FeatureGroup(name="Parks", show=True).add_to(m)
    folium.GeoJson(parks, fill_color = '#2C6E49', color = '#2C6E49', opacity = .5).add_to(fg2)

    folium.LayerControl(collapsed=False).add_to(m)
    return m
